config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  resources :books
  resources :users

  get "home/about" => "homes#about"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
 attachment :profile_image
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 has_many :books, dependent: :destroy

  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resourse)
    user_path(current_user.id)
  end

  # # def after_sign_out_path_for(resource)
  #   root_path
  # end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

 before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

    def create
        @book = Book.new(book_params)
        @book.user_id = current_user.id
        if  @book.save
            flash[:notice] = "successfully"
            redirect_to book_path(@book.id)
        else
            @books =  Book.all
            @user = current_user
            flash.now[:danger] = "error!"
            render :index
        end
    end

    def index
        @books =  Book.all
        @book = Book.new
        @user = current_user
    end

    def show
        @book = Book.new
        @books = Book.find(params[:id])
        @user = @books.user


    end

    def edit
        @book = Book.find(params[:id])
    end

    def update
        @book = Book.find(params[:id])
        if @book.update(book_params)
           flash[:notice] = "successfully"
           redirect_to book_path(@book.id)
        else
            render :edit
        end
    end

    def destroy
        @book = Book.find(params[:id])
        @book.destroy
        redirect_to books_path
    end


    private

    def book_params
        params.require(:book).permit(:title,:body)
    end

     def correct_user
        @book = Book.find(params[:id])
        @user = @book.user
        redirect_to(books_path) unless @user == current_user
     end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController


end

app/controllers/users_controller.rb
class UsersController < ApplicationController


    before_action :authenticate_user!
    before_action :correct_user, only: [:edit, :update]




    def create
        @book = Book.new(books_params)
        @book.user_id = current_user.id
        if @book.save
            flash[:notice] = "successfully"
            redirect_to book_path
        end
    end

    def index
        @users = User.all
        @book = Book.new
        @user = current_user
    end

    def show
        @user = User.find(params[:id])
        @books = @user.books
        @book = Book.new
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if  @user.update(user_params)
            flash[:notice] = "successfully"
            redirect_to user_path(@user.id)
        else
            flash.now[:danger] = "error!"
            render :edit
        end
    end

    private

    def user_params
        params.require(:user).permit(:name,:introduction,:profile_image)
    end

    def correct_user
        @user = User.find(params[:id])
        redirect_to user_path(current_user.id) unless @user == current_user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_index.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
    <%= link_to edit_user_path(user) ,class: "btn btn-block btn-outline-secondary", type: "button" do %>
      <span aria-hidden="true" class="fas fa-user-cog"></span>
    <% end %>
  </div>
  <h2>New book</h2>
    <% if book.errors.any? %>
      <%= book.errors.count %>errors exist!
      <% book.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    <% end %>

   <%= form_with model:book, local:true do |f| %>
   <h2>title</h2>
   <%= f.text_field :title %>
   <h2>Opinion</h2>
   <%= f.text_area :body %>
   <%= f.submit "Create Book" %>
   <% end %>
</div>

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
    <%= @book.errors.count %>errors exist!
    <% @book.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
<% end %>

<%= form_with  model:@book, local: true do |f| %>
  <h4>title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Update Book' %>
<% end %>
 <li>
   <%= link_to 'Show',book_path(@book.id) %>
 </li>
 <li>
   <%= link_to 'Back', books_path %>
 </li>

app/views/books/index.html.erb
<main>
  <%= flash[:notice] %>
  <%= flash.now[:danger] %>
    <div class="container px-5 px-sm-0">
      <div class="row">
        <%= render 'books/index', book: @book, user: @user %>
        <div class="col-md-8 offset-md-1">
          <h2>Books</h2>
          <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user.id) do %>
                  <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
                  <% end %>
                </td>
                <td><%= link_to book.title, book_path(book.id) %></td>
                <td><%= book.body %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
</main>

app/views/books/show.html.erb
<%= flash[:notice] %>
<%= flash.now[:danger] %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'books/index', book: @book, user: @user %>
    <div class="col-md-8 offset-md-1">
     <h2>Book detail</h2>
      <table class="table table-hover table-inverse">
        <tbody>
          <td><%= link_to user_path(@user.id) do %>
                <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
                <%= @books.user.name %>
              <% end %>
          </td>
          <td><%= @books.title %></td>
          <td><%= @books.body %></td>
          <% if @user.id == current_user.id %>
          <td><%= link_to "Edit", edit_book_path(@books.id) %></td>
          <td><%= link_to "Destroy", book_path,method: :delete %></td>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<main>
    <p id="notice"></p>
    <div class="container">
      <div class="row">
        <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
      </div>
    </div>
</main>

app/views/homes/top.html.erb
<h1>welcome to Bookers!!</h1>
<p>In Bookers</br>
<p>you can share and exchange your opinion, inpression, and emotion </br>
<p>about various books!</p>

<li>
    <%= link_to "log_in", new_user_session_path %><>
</li>
<li>
    <%= link_to "sign_up", new_user_registration_path %>
</li>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
    <p class="alert alert-<%= key %>">
      <%= value %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/f7fc5178dd.js" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark" >
        <div class="container">
          <a class="navbar-brand  p-3" href="/" >Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li><a class="fas fa-home nav-link text-light" href="/users/id"> Home</a></li>
              <li><a class="fas fa-users nav-link text-light" href="/users"> Users</a></li>
              <li><a class="fas fa-book-open nav-link text-light" href="/books"> Books</a></li>
              <li><a class="fas fa-sign-out-alt nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out"> Log out</a></li>
              <% else %>
               <li><a class="fas fa-home nav-link text-light" href="/"> Home</a></li>
               <li><a class="fas fa-link nav-link text-light" href="/home/about"> About</a></li>
               <li><a class="fas fa-user-plus nav-link text-light" href="/users/sign_up"> Sign up</a></li>
               <li><a class="fas fa-sign-in-alt nav-link text-light" href="/users/sign_in"> Log in</a></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<h1>User info</h1>
  <% if @user.errors.any? %>
    <%= @user.errors.count %>errors exist!!
    <%= @user.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>


  <%= form_with model:@user, local:true do |f| %>
  <h4>Name</h4>
  <%= f.text_field :name %>

  <h4>Image</h4>
  <%= f.attachment_field :profile_image, placeholder:'Create box' %>

  <h4>introduction</h4>
  <%= f.text_area :introduction %>
  <%= f.submit 'Update User' %>
<% end %>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'books/index', book: @book, user: @user %>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= flash[:notice] %>
  <%= flash.now[:danger] %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'books/index', book: @book, user: @user %>
    <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td><%= link_to user_path(@user.id) do %>
              <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  </div>
</div>